application: pro-touch
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /js
  static_dir: javascript

- url: /css
  static_dir: css

- url: /images
  static_dir: images

- url: /cleaning-process.*
  script: controllers.cleaningProcess.app

- url: /one-time-cleanings.*
  script: controllers.oneTimeCleanings.app

- url: /rotational-cleanings.*
  script: controllers.rotationalCleanings.app

- url: /our-mission.*
  script: controllers.mission.app

- url: /customer-testimonials.*
  script: controllers.customerReviews.app

- url: /our-staff.*
  script: controllers.staff.app

- url: .*
  script: controllers.main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest